(function() {
    'use strict';

    angular
        .module('app.sponser')
        .controller('Sponser', Sponser);

	function Sponser(){
		var vm = this;
		this.sponsers =[{ID: 1,
						Name: 'brenner',
						ImagePath:'Content/Images/clients/brenner.jpg',
						url:''			},
						{ID: 2,
						Name: 'Dawood',
						ImagePath:'Content/Images/clients/Dawood.jpg',
						url:''			},
						{ID: 3,
						Name: 'Hershey',
						ImagePath:'Content/Images/clients/herco_new.jpg',
						url:''			},
						{ID: 4,
						Name: 'Hersha',
						ImagePath:'Content/Images/clients/Hersha.jpg',
						url:''			},
						{ID: 5,
						Name: 'Metrobank',
						ImagePath:'Content/Images/clients/MetroLogo2-RdBlk.JPG',
						url:''			},
						{ID: 6,
						Name: 'Kumon',
						ImagePath:'Content/Images/clients/Kumon.jpg',
						url:''			},
						{ID: 7,
						Name: 'Holy Sprit',
						ImagePath:'Content/Images/clients/hs.jpg',
						url:''			},
						{ID: 8,
						Name: 'Morgan Stanely',
						ImagePath:'Content/Images/clients/MorganStanleyLogo.jpg',
						url:''			},
						{ID: 9,
						Name: 'pennmutual',
						ImagePath:'Content/Images/clients/pennmutual.jpg',
						url:''			},
						{ID: 10,
						Name: 'Pinnacle Health',
						ImagePath:'Content/Images/clients/PH_Proven.jpg',
						url:''			},
						{ID: 11,
						Name: 'PNC',
						ImagePath:'Content/Images/clients/PNC.jpg',
						url:''			},
						{ID: 12,
						Name: 'Passage to India',
						ImagePath:'Content/Images/clients/PTILogo.jpg',
						url:''			},
						{ID: 13,
						Name: 'schien',
						ImagePath:'Content/Images/clients/schien.jpg',
						url:''			},
						{ID: 14,
						Name: 'SimRaj',
						ImagePath:'Content/Images/clients/SimRaj.jpg',
						url:''			},
						{ID: 15,
						Name: 'SusquehannaBank',
						ImagePath:'Content/Images/clients/SusquehannaBank.jpg',
						url:''			},
						{ID: 16,
						Name: 'VallyAgency',
						ImagePath:'Content/Images/clients/VallyAgency.png',
						url:''			},
						{ID: 17,
						Name: 'XpertVantage',
						ImagePath:'Content/Images/clients/XpertVantage.jpg',
						url:''			},
						{ID: 18,
						Name: 'Nita',
						ImagePath:'Content/Images/clients/Nita.jpg',
						url:''		},
						{ID: 19,
						Name: 'M&T',
						ImagePath:'Content/Images/clients/M&TLogo.jpg',
						url:''		},
						{ID: 20,
						Name: 'legacy_logo_final',
						ImagePath:'Content/Images/clients/legacy_logo_final.jpg',
						url:''		}
						];

	}


    })();